// Generated by gencpp from file gazebo_ros_battery/ResetRequest.msg
// DO NOT EDIT!


#ifndef GAZEBO_ROS_BATTERY_MESSAGE_RESETREQUEST_H
#define GAZEBO_ROS_BATTERY_MESSAGE_RESETREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Bool.h>

namespace gazebo_ros_battery
{
template <class ContainerAllocator>
struct ResetRequest_
{
  typedef ResetRequest_<ContainerAllocator> Type;

  ResetRequest_()
    : reset()  {
    }
  ResetRequest_(const ContainerAllocator& _alloc)
    : reset(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Bool_<ContainerAllocator>  _reset_type;
  _reset_type reset;





  typedef boost::shared_ptr< ::gazebo_ros_battery::ResetRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gazebo_ros_battery::ResetRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ResetRequest_

typedef ::gazebo_ros_battery::ResetRequest_<std::allocator<void> > ResetRequest;

typedef boost::shared_ptr< ::gazebo_ros_battery::ResetRequest > ResetRequestPtr;
typedef boost::shared_ptr< ::gazebo_ros_battery::ResetRequest const> ResetRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gazebo_ros_battery::ResetRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gazebo_ros_battery::ResetRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gazebo_ros_battery::ResetRequest_<ContainerAllocator1> & lhs, const ::gazebo_ros_battery::ResetRequest_<ContainerAllocator2> & rhs)
{
  return lhs.reset == rhs.reset;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gazebo_ros_battery::ResetRequest_<ContainerAllocator1> & lhs, const ::gazebo_ros_battery::ResetRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gazebo_ros_battery

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gazebo_ros_battery::ResetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_ros_battery::ResetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_ros_battery::ResetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_ros_battery::ResetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_ros_battery::ResetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_ros_battery::ResetRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gazebo_ros_battery::ResetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "192b1618ba2ef027b56fe4cf66db1afe";
  }

  static const char* value(const ::gazebo_ros_battery::ResetRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x192b1618ba2ef027ULL;
  static const uint64_t static_value2 = 0xb56fe4cf66db1afeULL;
};

template<class ContainerAllocator>
struct DataType< ::gazebo_ros_battery::ResetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gazebo_ros_battery/ResetRequest";
  }

  static const char* value(const ::gazebo_ros_battery::ResetRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gazebo_ros_battery::ResetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Bool reset\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Bool\n"
"bool data\n"
;
  }

  static const char* value(const ::gazebo_ros_battery::ResetRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gazebo_ros_battery::ResetRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reset);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResetRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gazebo_ros_battery::ResetRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gazebo_ros_battery::ResetRequest_<ContainerAllocator>& v)
  {
    s << indent << "reset: ";
    s << std::endl;
    Printer< ::std_msgs::Bool_<ContainerAllocator> >::stream(s, indent + "  ", v.reset);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAZEBO_ROS_BATTERY_MESSAGE_RESETREQUEST_H
