// Generated by gencpp from file gazebo_ros_battery/SetCharge.msg
// DO NOT EDIT!


#ifndef GAZEBO_ROS_BATTERY_MESSAGE_SETCHARGE_H
#define GAZEBO_ROS_BATTERY_MESSAGE_SETCHARGE_H

#include <ros/service_traits.h>


#include <gazebo_ros_battery/SetChargeRequest.h>
#include <gazebo_ros_battery/SetChargeResponse.h>


namespace gazebo_ros_battery
{

struct SetCharge
{

typedef SetChargeRequest Request;
typedef SetChargeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetCharge
} // namespace gazebo_ros_battery


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_ros_battery::SetCharge > {
  static const char* value()
  {
    return "d7cc9c3639e823f359c406523bae8d4a";
  }

  static const char* value(const ::gazebo_ros_battery::SetCharge&) { return value(); }
};

template<>
struct DataType< ::gazebo_ros_battery::SetCharge > {
  static const char* value()
  {
    return "gazebo_ros_battery/SetCharge";
  }

  static const char* value(const ::gazebo_ros_battery::SetCharge&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_ros_battery::SetChargeRequest> should match
// service_traits::MD5Sum< ::gazebo_ros_battery::SetCharge >
template<>
struct MD5Sum< ::gazebo_ros_battery::SetChargeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_ros_battery::SetCharge >::value();
  }
  static const char* value(const ::gazebo_ros_battery::SetChargeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_ros_battery::SetChargeRequest> should match
// service_traits::DataType< ::gazebo_ros_battery::SetCharge >
template<>
struct DataType< ::gazebo_ros_battery::SetChargeRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_ros_battery::SetCharge >::value();
  }
  static const char* value(const ::gazebo_ros_battery::SetChargeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_ros_battery::SetChargeResponse> should match
// service_traits::MD5Sum< ::gazebo_ros_battery::SetCharge >
template<>
struct MD5Sum< ::gazebo_ros_battery::SetChargeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_ros_battery::SetCharge >::value();
  }
  static const char* value(const ::gazebo_ros_battery::SetChargeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_ros_battery::SetChargeResponse> should match
// service_traits::DataType< ::gazebo_ros_battery::SetCharge >
template<>
struct DataType< ::gazebo_ros_battery::SetChargeResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_ros_battery::SetCharge >::value();
  }
  static const char* value(const ::gazebo_ros_battery::SetChargeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_ROS_BATTERY_MESSAGE_SETCHARGE_H
