// Generated by gencpp from file gazebo_ros_battery/SetTemperature.msg
// DO NOT EDIT!


#ifndef GAZEBO_ROS_BATTERY_MESSAGE_SETTEMPERATURE_H
#define GAZEBO_ROS_BATTERY_MESSAGE_SETTEMPERATURE_H

#include <ros/service_traits.h>


#include <gazebo_ros_battery/SetTemperatureRequest.h>
#include <gazebo_ros_battery/SetTemperatureResponse.h>


namespace gazebo_ros_battery
{

struct SetTemperature
{

typedef SetTemperatureRequest Request;
typedef SetTemperatureResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTemperature
} // namespace gazebo_ros_battery


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_ros_battery::SetTemperature > {
  static const char* value()
  {
    return "cff89ed8489cfa6e56ffd34457ea253c";
  }

  static const char* value(const ::gazebo_ros_battery::SetTemperature&) { return value(); }
};

template<>
struct DataType< ::gazebo_ros_battery::SetTemperature > {
  static const char* value()
  {
    return "gazebo_ros_battery/SetTemperature";
  }

  static const char* value(const ::gazebo_ros_battery::SetTemperature&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_ros_battery::SetTemperatureRequest> should match
// service_traits::MD5Sum< ::gazebo_ros_battery::SetTemperature >
template<>
struct MD5Sum< ::gazebo_ros_battery::SetTemperatureRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_ros_battery::SetTemperature >::value();
  }
  static const char* value(const ::gazebo_ros_battery::SetTemperatureRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_ros_battery::SetTemperatureRequest> should match
// service_traits::DataType< ::gazebo_ros_battery::SetTemperature >
template<>
struct DataType< ::gazebo_ros_battery::SetTemperatureRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_ros_battery::SetTemperature >::value();
  }
  static const char* value(const ::gazebo_ros_battery::SetTemperatureRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_ros_battery::SetTemperatureResponse> should match
// service_traits::MD5Sum< ::gazebo_ros_battery::SetTemperature >
template<>
struct MD5Sum< ::gazebo_ros_battery::SetTemperatureResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_ros_battery::SetTemperature >::value();
  }
  static const char* value(const ::gazebo_ros_battery::SetTemperatureResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_ros_battery::SetTemperatureResponse> should match
// service_traits::DataType< ::gazebo_ros_battery::SetTemperature >
template<>
struct DataType< ::gazebo_ros_battery::SetTemperatureResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_ros_battery::SetTemperature >::value();
  }
  static const char* value(const ::gazebo_ros_battery::SetTemperatureResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_ROS_BATTERY_MESSAGE_SETTEMPERATURE_H
