// Generated by gencpp from file gazebo_ros_battery/SetTemperatureResponse.msg
// DO NOT EDIT!


#ifndef GAZEBO_ROS_BATTERY_MESSAGE_SETTEMPERATURERESPONSE_H
#define GAZEBO_ROS_BATTERY_MESSAGE_SETTEMPERATURERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float32.h>

namespace gazebo_ros_battery
{
template <class ContainerAllocator>
struct SetTemperatureResponse_
{
  typedef SetTemperatureResponse_<ContainerAllocator> Type;

  SetTemperatureResponse_()
    : temperature()  {
    }
  SetTemperatureResponse_(const ContainerAllocator& _alloc)
    : temperature(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float32_<ContainerAllocator>  _temperature_type;
  _temperature_type temperature;





  typedef boost::shared_ptr< ::gazebo_ros_battery::SetTemperatureResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gazebo_ros_battery::SetTemperatureResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetTemperatureResponse_

typedef ::gazebo_ros_battery::SetTemperatureResponse_<std::allocator<void> > SetTemperatureResponse;

typedef boost::shared_ptr< ::gazebo_ros_battery::SetTemperatureResponse > SetTemperatureResponsePtr;
typedef boost::shared_ptr< ::gazebo_ros_battery::SetTemperatureResponse const> SetTemperatureResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gazebo_ros_battery::SetTemperatureResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gazebo_ros_battery::SetTemperatureResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gazebo_ros_battery::SetTemperatureResponse_<ContainerAllocator1> & lhs, const ::gazebo_ros_battery::SetTemperatureResponse_<ContainerAllocator2> & rhs)
{
  return lhs.temperature == rhs.temperature;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gazebo_ros_battery::SetTemperatureResponse_<ContainerAllocator1> & lhs, const ::gazebo_ros_battery::SetTemperatureResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gazebo_ros_battery

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gazebo_ros_battery::SetTemperatureResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_ros_battery::SetTemperatureResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_ros_battery::SetTemperatureResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_ros_battery::SetTemperatureResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_ros_battery::SetTemperatureResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_ros_battery::SetTemperatureResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gazebo_ros_battery::SetTemperatureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef84ef3026ebaa21b37f5b167de3d809";
  }

  static const char* value(const ::gazebo_ros_battery::SetTemperatureResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef84ef3026ebaa21ULL;
  static const uint64_t static_value2 = 0xb37f5b167de3d809ULL;
};

template<class ContainerAllocator>
struct DataType< ::gazebo_ros_battery::SetTemperatureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gazebo_ros_battery/SetTemperatureResponse";
  }

  static const char* value(const ::gazebo_ros_battery::SetTemperatureResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gazebo_ros_battery::SetTemperatureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float32 temperature\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float32\n"
"float32 data\n"
;
  }

  static const char* value(const ::gazebo_ros_battery::SetTemperatureResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gazebo_ros_battery::SetTemperatureResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.temperature);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetTemperatureResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gazebo_ros_battery::SetTemperatureResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gazebo_ros_battery::SetTemperatureResponse_<ContainerAllocator>& v)
  {
    s << indent << "temperature: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.temperature);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAZEBO_ROS_BATTERY_MESSAGE_SETTEMPERATURERESPONSE_H
