(cl:defpackage gazebo_ros_battery-srv
  (:use )
  (:export
   "RESET"
   "<RESET-REQUEST>"
   "RESET-REQUEST"
   "<RESET-RESPONSE>"
   "RESET-RESPONSE"
   "SETCHARGE"
   "<SETCHARGE-REQUEST>"
   "SETCHARGE-REQUEST"
   "<SETCHARGE-RESPONSE>"
   "SETCHARGE-RESPONSE"
   "SETTEMPERATURE"
   "<SETTEMPERATURE-REQUEST>"
   "SETTEMPERATURE-REQUEST"
   "<SETTEMPERATURE-RESPONSE>"
   "SETTEMPERATURE-RESPONSE"
  ))

