// Generated by gencpp from file battery_exploration/battery_station.msg
// DO NOT EDIT!


#ifndef BATTERY_EXPLORATION_MESSAGE_BATTERY_STATION_H
#define BATTERY_EXPLORATION_MESSAGE_BATTERY_STATION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace battery_exploration
{
template <class ContainerAllocator>
struct battery_station_
{
  typedef battery_station_<ContainerAllocator> Type;

  battery_station_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , orientation_x(0.0)
    , orientation_y(0.0)
    , orientation_z(0.0)
    , orientation_w(0.0)
    , distance(0.0)  {
    }
  battery_station_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , orientation_x(0.0)
    , orientation_y(0.0)
    , orientation_z(0.0)
    , orientation_w(0.0)
    , distance(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _orientation_x_type;
  _orientation_x_type orientation_x;

   typedef float _orientation_y_type;
  _orientation_y_type orientation_y;

   typedef float _orientation_z_type;
  _orientation_z_type orientation_z;

   typedef float _orientation_w_type;
  _orientation_w_type orientation_w;

   typedef float _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::battery_exploration::battery_station_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::battery_exploration::battery_station_<ContainerAllocator> const> ConstPtr;

}; // struct battery_station_

typedef ::battery_exploration::battery_station_<std::allocator<void> > battery_station;

typedef boost::shared_ptr< ::battery_exploration::battery_station > battery_stationPtr;
typedef boost::shared_ptr< ::battery_exploration::battery_station const> battery_stationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::battery_exploration::battery_station_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::battery_exploration::battery_station_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::battery_exploration::battery_station_<ContainerAllocator1> & lhs, const ::battery_exploration::battery_station_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.orientation_x == rhs.orientation_x &&
    lhs.orientation_y == rhs.orientation_y &&
    lhs.orientation_z == rhs.orientation_z &&
    lhs.orientation_w == rhs.orientation_w &&
    lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::battery_exploration::battery_station_<ContainerAllocator1> & lhs, const ::battery_exploration::battery_station_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace battery_exploration

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::battery_exploration::battery_station_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::battery_exploration::battery_station_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::battery_exploration::battery_station_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::battery_exploration::battery_station_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::battery_exploration::battery_station_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::battery_exploration::battery_station_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::battery_exploration::battery_station_<ContainerAllocator> >
{
  static const char* value()
  {
    return "66744cc284356957a3941b5cf863c900";
  }

  static const char* value(const ::battery_exploration::battery_station_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x66744cc284356957ULL;
  static const uint64_t static_value2 = 0xa3941b5cf863c900ULL;
};

template<class ContainerAllocator>
struct DataType< ::battery_exploration::battery_station_<ContainerAllocator> >
{
  static const char* value()
  {
    return "battery_exploration/battery_station";
  }

  static const char* value(const ::battery_exploration::battery_station_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::battery_exploration::battery_station_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 orientation_x\n"
"float32 orientation_y\n"
"float32 orientation_z\n"
"float32 orientation_w\n"
"float32 distance\n"
;
  }

  static const char* value(const ::battery_exploration::battery_station_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::battery_exploration::battery_station_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.orientation_x);
      stream.next(m.orientation_y);
      stream.next(m.orientation_z);
      stream.next(m.orientation_w);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct battery_station_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::battery_exploration::battery_station_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::battery_exploration::battery_station_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "orientation_x: ";
    Printer<float>::stream(s, indent + "  ", v.orientation_x);
    s << indent << "orientation_y: ";
    Printer<float>::stream(s, indent + "  ", v.orientation_y);
    s << indent << "orientation_z: ";
    Printer<float>::stream(s, indent + "  ", v.orientation_z);
    s << indent << "orientation_w: ";
    Printer<float>::stream(s, indent + "  ", v.orientation_w);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BATTERY_EXPLORATION_MESSAGE_BATTERY_STATION_H
